# Generated by Django 4.1.1 on 2022-10-31 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("roll", models.CharField(max_length=12)),
                ("room", models.CharField(max_length=6)),
                ("rf_id", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("B", "Breakfast"),
                            ("L", "Lunch"),
                            ("S", "Snacks"),
                            ("D", "Dinner"),
                        ],
                        max_length=5,
                    ),
                ),
                ("weight", models.CharField(max_length=6)),
                ("date", models.DateField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mess.student"
                    ),
                ),
            ],
        ),
    ]
