# Generated by Django 4.1.1 on 2022-11-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mess", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ("rollNumber",)},
        ),
        migrations.RenameField(
            model_name="student",
            old_name="roll",
            new_name="rollNumber",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="room",
            new_name="roomNumber",
        ),
    ]
