# Generated by Django 4.1.1 on 2022-11-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mess", "0002_alter_student_options_rename_roll_student_rollnumber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
    ]
