# Generated by Django 4.1.1 on 2022-11-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mess", "0004_alter_student_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="status",
        ),
        migrations.AddField(
            model_name="student",
            name="permission",
            field=models.CharField(
                choices=[("A", "Allowed"), ("T", "Taken"), ("NA", "Not Allowed")],
                default="Allowed",
                max_length=10,
            ),
        ),
    ]
