# Generated by Django 4.1.1 on 2022-11-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mess", "0005_remove_student_status_student_permission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="rf_id",
            new_name="RFID",
        ),
        migrations.AlterField(
            model_name="student",
            name="permission",
            field=models.CharField(
                choices=[("A", "Allowed"), ("NA", "Not Allowed")],
                default="A",
                max_length=10,
            ),
        ),
    ]
