# Generated by Django 4.1.1 on 2022-11-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mess", "0006_rename_rf_id_student_rfid_alter_student_permission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meal",
            options={"ordering": ["date"]},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["rollNumber"]},
        ),
    ]
