# Generated by Django 4.1.3 on 2022-11-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0007_alter_meal_options_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='RFID',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
