# Generated by Django 4.1.3 on 2022-11-14 10:28

from django.db import migrations, models
import mess.models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0008_alter_student_rfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='mess/media'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollNumber',
            field=models.CharField(max_length=12, validators=[mess.models.ID_valid]),
        ),
    ]
