# Generated by Django 4.1.3 on 2022-11-14 11:21

from django.db import migrations, models
import mess.models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0009_student_photo_alter_student_rollnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollNumber',
            field=models.CharField(max_length=12, unique=True, validators=[mess.models.ID_valid]),
        ),
    ]
