# Generated by Django 4.1.3 on 2022-11-14 17:58

from django.db import migrations, models
import mess.models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0010_alter_student_rollnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to=mess.models.image_handler),
        ),
    ]
