# Generated by Django 4.1.3 on 2022-11-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0011_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='RFID',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
