# Generated by Django 4.1.3 on 2022-11-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0013_announcement_alter_student_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
