# Generated by Django 4.1.3 on 2022-11-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0014_announcement_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mess/menu/')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='RFID',
            field=models.CharField(blank=True, max_length=15, null=None, unique=True),
        ),
    ]
