# Generated by Django 4.1.3 on 2022-11-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0015_menu_alter_student_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='RFID',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
