# Generated by Django 4.1.3 on 2022-11-18 17:50

from django.db import migrations, models
import mess.models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0016_alter_student_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default.png', upload_to=mess.models.image_handler),
        ),
    ]
