# Generated by Django 4.1.3 on 2022-11-18 18:18

import datetime
from django.db import migrations, models
import mess.models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0017_alter_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='end',
            field=models.DateField(default=datetime.datetime(2022, 11, 18, 23, 48, 37, 232825)),
        ),
        migrations.AddField(
            model_name='menu',
            name='start',
            field=models.DateField(default=datetime.datetime(2022, 11, 18, 23, 48, 37, 232825)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='file',
            field=models.FileField(upload_to=mess.models.menu_handler),
        ),
    ]
