# Generated by Django 4.1.3 on 2022-11-18 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0018_menu_end_menu_start_alter_menu_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='menu',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
