# Generated by Django 4.1.3 on 2022-11-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0019_alter_menu_end_alter_menu_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='RFID',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
