# Generated by Django 4.1.3 on 2022-11-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0020_alter_student_rfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alias',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
