# Generated by Django 4.1.3 on 2022-12-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0021_student_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='heading',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='announcement',
            name='issueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
