# Generated by Django 4.1.3 on 2022-12-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0022_announcement_heading_announcement_issuedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='heading',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='issueDate',
            field=models.DateField(),
        ),
    ]
