# Generated by Django 4.1.3 on 2022-12-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0023_alter_announcement_heading_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['start']},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='end',
        ),
    ]
