# Generated by Django 4.1.3 on 2022-12-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0024_alter_menu_options_remove_menu_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='weight',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
