# Generated by Django 4.1.3 on 2022-12-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0026_alter_meal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-date', 'student__rollNumber']},
        ),
        migrations.AlterField(
            model_name='meal',
            name='weight',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
