# Generated by Django 4.0.6 on 2022-12-13 16:54

from django.db import migrations, models
import mess.models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0027_alter_meal_options_alter_meal_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='avatar.jpg', upload_to=mess.models.image_handler),
        ),
    ]
