# Generated by Django 4.1.3 on 2022-12-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0028_alter_student_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['rollNumber', 'name']},
        ),
    ]
