# Generated by Django 4.1.3 on 2023-01-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0029_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='alias',
            field=models.CharField(blank=True, default='User', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='permission',
            field=models.CharField(choices=[('A', 'Allowed'), ('NA', 'Not Allowed')], default='A', max_length=10),
        ),
    ]
